# docker-compose.prod.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: gestionmysoutenance_app_prod
    restart: unless-stopped
    volumes:
      - app_prod_storage:/var/www/html/storage
      - app_prod_bootstrap_cache:/var/www/html/bootstrap/cache
    ports:
      - "80:80"
    env_file:
      - .env.prod
    networks:
      - app-network

  db_prod:
    image: mysql:8.3
    container_name: gestionmysoutenance_db_prod
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_prod_data:/var/lib/mysql
      - ./mysoutenance.sql:/docker-entrypoint-initdb.d/mysoutenance.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env.prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_prod_data:
    driver: local
  app_prod_storage:
    driver: local
  app_prod_bootstrap_cache:
    driver: local
